### ISSUE TITLE
(deleted)

### ISSUE THREAD

**Issue by pitsi** [Twilight0/plugin.video.antenna.gr#6]

**Comment by kimondiomis94** [comment]
I would agree to this issue too

**Comment by Twilight0** [comment]
They no longer have the website operational as it was, they only have an app for mobile platforms which probably requires sign-up. I might try mimicking the app behaviour, but this will definitely take a lot of time and effort.

**Comment by pitsi** [comment]
Are you on linux? Some say that the site is functional only in chrome on windows. In firefox it just shows the prompt to download the mobile app.
For me (firefox, chrome and brave under linux) the site looks the same as in firefox on windows, no difference at all.

On top of the above, I think the only difference now is that all urls of
`www.antenna.gr`
have changed to 
`vod.antenna.gr`

**Comment by Twilight0** [comment]
Yes I use Linux with Vivaldi. Will try this out soon enough.

**Comment by pitsi** [comment]
Then try f12 > network conditions > user agent > untick "use browser default" and select "chrome - windows" from the list below.

**Comment by Twilight0** [comment]
Yes, it works. I can probably have the cookies stored as guest for each addon user as well, or use his own credentials, will see.

**Comment by pitsi** [comment]
In case it helps, I just learned that one can use any random email to create an account, as the page sends no confirmation email back.

**Comment by Twilight0** [comment]
Yes it probably does, but I will see if I can avoid using it. The point is that their new website has far less content, than it used to. For example many old series are no longer present.

**Comment by pitsi** [comment]
It has been almost a month now and the site is changing all the time and always for the worse. If you can not find a way to make it work, don't waste your time. Feel free to close this issue, remove the addon from the repo and call it a "wontfix" (mozilla's term for issues that can/will not be solved).

**Comment by Twilight0** [comment]
> It has been almost a month now and the site is changing all the time and always for the worse. If you can not find a way to make it work, don't waste your time. Feel free to close this issue, remove the addon from the repo and call it a "wontfix" (mozilla's term for issues that can/will not be solved).

Exactly my thoughts, the website is constantly changing and it does not worth the effort, I suppose the dust will settle from now on that Euro championship has been completed and the new season from September will come. Then will examine possible solution.

**Comment by pitsi** [comment]
Keep in mind that antenna will also broadcast the next world cup (mid October 2022 to mid November 2022). That's why I do not expect anything to change until then.

**Comment by pitsi** [comment]
So, I just discovered from a tweet of yours that the addon was updated to v3.x and I reinstalled it. You are 100% right on how difficult it is to scrap their shitty site and I respect your work and efforts on that. However, as I am interested in vod only, the addon has no use for me at its current state, so I will remove it again.

But before I remove it, I would like to point out a small issue. The link to youtube channel does not work and pops this in the log
```
2021-12-26 08:31:03.254 T:140259270018816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'plugin.video.antenna.gr'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 565, in _on_channel
                                                resource_manager = self.get_resource_manager(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 411, in get_resource_manager
                                                self._resource_manager = ResourceManager(context, self.get_client(context))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 292, in get_client
                                                access_manager.update_dev_access_token(dev_id, '')
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/access_manager.py", line 318, in update_dev_access_token
                                                self._json['access_manager']['developers'][addon_id]['access_token'] = access_token
                                            KeyError: 'plugin.video.antenna.gr'
                                            -->End of Python script error report<--
2021-12-26 08:31:03.397 T:140259285980928   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/channel/UC0smvAbfczoN75dP0Hw4Pzw/?addon_id=plugin.video.antenna.gr
2021-12-26 08:31:03.411 T:140260810786944   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/channel/UC0smvAbfczoN75dP0Hw4Pzw/?addon_id=plugin.video.antenna.gr) failed
```
Kodi 18.9 on libeelec 9.2.6 x64. Youtube (searches etc) works fine, so it is not an api key issue.

**Comment by Twilight0** [comment]
@pitsi Try removing api_keys.json through youtube addon's settings. I am also closing the issue since basically it does not apply anymore.

**Comment by pitsi** [comment]
Why should I do that? The keys are a big pita to install correctly (in any way, e.g via the addon, via the file or via the web interface), and I do not want to remove and reinstall them for no reason! As I said above, youtube does work with no issues.

**Comment by Twilight0** [comment]
Your own api keys are already part of the settings, api_keys.json is where youtube addon stores the keys from other addons from developers when they are "registered", its no harm to delete it. You can keep a backup and restore it in case something bad happens.
